setup.townData = {
  'name': {
    'prefix': ['Green', 'Elms', 'Oak', 'Fair', 'Farren', 'Tall', 'Nar', 'Alla', 'Lans', 'San', 'Col', 'Fri', 'Plain', 'Hon', 'Far', 'Barrow', 'Shi', 'Mel', 'Mal', 'Bon', 'Bie', 'Can', 'Pol', 'Pan', 'Fald', 'Frior', 'Pol', 'Stone', 'Water', 'Leaf', 'Ice', 'Flame', 'Sol', 'Storm', 'Earth', 'Gleam', 'Star', 'Art', 'War', 'Heart', 'Hard', 'Fall', 'Rock', 'Doom', 'Oak', 'Tear', 'Raven', 'Badger', 'Snake', 'Lion', 'Hell', 'Rage', 'Brine', 'Rat', 'Buck', 'Lily', 'Core', 'Stench', 'Mage', 'God', 'Soil', 'Pure', 'Mal', 'Cam', 'Fen', 'Clear', 'Split', 'Founders', 'Heir', 'Fair', 'Spin'],
    'suffix': ['dale', 'ten', 'den', 'ven', 'gen', 'len', 'lun', 'stun', 'ville', 'burn', 'view', 'nen', 'lan', 'sed', 'folk', 'ork', 'len', 'pan', 'rel', 'old', 'ten', 'tan', 'lend', 'vorn', 'vant', 'lid', 'lin', 'crest', 'bridge', 'run', 'catch', 'blade', 'haven', 'rise', 'more', 'light', 'main', 'blaze', 'place', 'tear', 'fold', 'rest', 'host', 'craft', 'lair', 'hollow', 'vale', 'hammer', 'pike', 'rail', 'spike', 'ring', 'henge', 'coil', 'spring', 'jaw', 'mark', 'hail', 'loch', 'child', 'keep', 'fort', 'brook', 'forth', 'melt', 'borourgh', 'ford', 'crawl', 'moral', 'combe', 'glen', 'garden', 'wish', 'fellow', 'ridge', 'ward']
  },
  'type': {
    'hamlet': {
      'population': random(30, 300),
      'wealthRoll': -20,
      'reputationRoll': -40,
      'sinRoll': -25,
      'diversityRoll': -20
    },
    'village': {
      'population': random(301, 1000),
      'wealthRoll': -10,
      'reputationRoll': -20,
      'sinRoll': -15,
      'diversityRoll': 10
    },
    'town': {
      'population': random(1001, 3000),
      'wealthRoll': 15,
      'reputationRoll': 5,
      'sinRoll': 5,
      'diversityRoll': 15
    },
    'city': {
      'population': random(3001, 6000),
      'wealthRoll': 5,
      'reputationRoll': 20,
      'sinRoll': 25,
      'diversityRoll': 25
    }
  },

  'economicIdeology': {
    'feudalism': {
      'economicsRoll': 15,
      'welfareRoll': -25,
      'lawRoll': 15,
      'militaryRoll': 20,
      'economicIdeologyIC': 'feudalistic',
      'economicIdeologyIST': 'feudalist',
      'economicIdeologyDescription': "The people of _town.name work the land in exchange for working their lord's lands."
    },
    'capitalism': {
      'economicsRoll': -20,
      'welfareRoll': -25,
      'lawRoll': 15,
      'militaryRoll': 20,
      'economicIdeologyIC': 'capitalistic',
      'economicIdeologyIST': 'capitalist',
      'economicIdeologyDescription': 'The people of _town.name work in exchange for payment from their employers, which they use to buy the necessities.'
    },
    'syndicalism': {
      'economicsRoll': 35,
      'welfareRoll': 25,
      'lawRoll': -15,
      'militaryRoll': -15,
      'economicIdeologyIC': 'syndicalistic',
      'economicIdeologyIST': 'syndicalist',
      'economicIdeologyDescription': 'The people of _town.name own the lands they work on collectively, and together benefit from its prosperity.'
    },
    'communism': {
      'economicsRoll': 40,
      'welfareRoll': 30,
      'lawRoll': -15,
      'militaryRoll': -30,
      'economicIdeologyIC': 'communistic',
      'economicIdeologyIST': 'communist',
      'economicIdeologyDescription': 'The people of _town.name work the jobs that they are able to, and are paid according to their needs. Excess profits are reinvested to strengthen the society as a whole.'
    },
    'primitivism': {
      'economicsRoll': 40,
      'welfareRoll': -25,
      'lawRoll': -30,
      'militaryRoll': -30,
      'economicIdeologyIC': 'primitivistic',
      'economicIdeologyIST': 'primitivist',
      'economicIdeologyDescription': "The people of _town.name work the land in a loosely organised sense; there is no concept of ownership, and the majority of the _town.type's citizens are hunter-gatherers."
    }
  },
  'politicalSource': {
    'absolute monarchy': {
      'politicalIdeology': ['autocracy', 'autocracy', 'autocracy', 'meritocracy', 'democracy', 'kleptocracy', 'magocracy', 'militocracy', 'oligarchy', 'pedocracy', 'theocracy', 'technocracy'],
      'autocracy': {
        'politicalSourceDescription': '<<print _townRuler.title.toUpperFirst()>> <<profile _townRuler>> is technically the head of state, but affairs are handled by the prime minister, <<profile _townLeader>>, who controls all executive decisions.'
      },
      'default': {
        'politicalSourceDescription': '<<print _townRuler.title.toUpperFirst()>> <<profile _townRuler>> is technically the head of state, but affairs are handled by a parliamentary consisting of _town.leaderType, the head of whom is _townLeader.title <<profile _townLeader>>.'
      }
    },
    'constitutional monarchy': {
      'politicalIdeology': ['autocracy', 'autocracy', 'meritocracy', 'democracy', 'democracy', 'democracy', 'kleptocracy', 'magocracy', 'militocracy', 'oligarchy', 'pedocracy', 'theocracy', 'technocracy'],
      'autocracy': {
        'politicalSourceDescription': "<<print _townLeader.title.toUpperFirst()>> <<profile _townLeader>> is the supreme ruler, and all laws and affairs are governed by the crowns' will."
      },
      'default': {
        'politicalSourceDescription': '<<print _townRuler.title.toUpperFirst()>> <<profile _townRuler>> is the head of state, but affairs are handled by _town.leaderType, the head of whom is _townLeader.title <<profile _townLeader>>.'
      }
    },
    'republic': {
      'politicalIdeology': ['meritocracy', 'meritocracy', 'democracy', 'democracy', 'democracy', 'democracy', 'kleptocracy', 'magocracy', 'militocracy', 'oligarchy', 'pedocracy', 'theocracy', 'technocracy'],
      'politicalSourceDescription': 'Affairs are handled by _town.leaderType, the head of whom is _townLeader.title <<profile _townLeader>>'
    },
    'anarchy': {
      'politicalIdeology': ['meritocracy', 'meritocracy', 'democracy', 'democracy', 'democracy', 'democracy', 'kleptocracy', 'magocracy', 'militocracy', 'oligarchy', 'pedocracy', 'theocracy', 'technocracy'],
      'politicalSourceDescription': 'None take responsibility for the stewardship of _town.name, but _town.leaderType hold the best semblance of order, the head of whom is _townLeader.title <<profile _townLeader>>.'
    }
  },
  'politicalIdeology': {
    'autocracy': {
      'economicsRoll': 45,
      'welfareRoll': -25,
      'lawRoll': 15,
      'militaryRoll': 25,
      'arcanaRoll': -5,
      'leaderType': 'the supreme leader',
      'type': 'nobles',
      'hasClass': false,
      'dndclass': 'noble',
      'background': 'noble',
      'title': 'Lord',
      'politicalIdeologyIC': 'autocratic'

    },
    'meritocracy': {
      'economicsRoll': 15,
      'welfareRoll': 5,
      'lawRoll': -5,
      'militaryRoll': -5,
      'arcanaRoll': 15,
      'leaderType': 'the competent',
      'type': 'commoners',
      'hasClass': false,
      'dndclass': 'noble',
      'background': 'noble',
      'title': 'Lord',
      'politicalIdeologyIC': 'meritocratic'
    },
    'democracy': {
      'economicsRoll': -15,
      'welfareRoll': 25,
      'lawRoll': 15,
      'militaryRoll': -5,
      'arcanaRoll': 15,
      'leaderType': 'the people',
      'type': 'commoners',
      'hasClass': false,
      'dndclass': 'commoner',
      'background': 'commoner',
      'title': 'Lord',
      'politicalIdeologyIC': 'democratic'
    },
    'kleptocracy': {
      'economicsRoll': -35,
      'welfareRoll': -25,
      'lawRoll': -30,
      'militaryRoll': -5,
      'arcanaRoll': 15,
      'leaderType': "the Thieves' Guild",
      'type': 'thieves',
      'hasClass': true,
      'dndclass': 'rogue',
      'background': 'criminal',
      'title': 'High Thief',
      'politicalIdeologyIC': 'kleptocratic'
    },
    'magocracy': {
      'economicsRoll': 2,
      'welfareRoll': 5,
      'lawRoll': -5,
      'militaryRoll': -5,
      'arcanaRoll': 50,
      'leaderType': 'the wizards',
      'type': 'wizards',
      'hasClass': true,
      'dndclass': 'wizard',
      'background': 'scholar',
      'title': 'Archchancellor',
      'politicalIdeologyIC': 'magocratic'
    },
    'militocracy': {
      'economicsRoll': 25,
      'welfareRoll': -5,
      'lawRoll': 30,
      'militaryRoll': 50,
      'arcanaRoll': -15,
      'leaderType': 'the military',
      'hasClass': true,
      'dndclass': 'fighter',
      'background': 'soldier',
      'title': 'Commander',
      'politicalIdeologyIC': 'militocratic'
    },
    'oligarchy': {
      'economicsRoll': 15,
      'welfareRoll': -15,
      'lawRoll': 5,
      'militaryRoll': 5,
      'arcanaRoll': -5,
      'leaderType': 'the powerful few',
      'type': 'nobles',
      'hasClass': false,
      'dndclass': 'noble',
      'background': 'noble',
      'title': 'Lord',
      'politicalIdeologyIC': 'oligarchic'
    },
    'pedocracy': {
      'economicsRoll': 15,
      'welfareRoll': 50,
      'lawRoll': -5,
      'militaryRoll': -5,
      'arcanaRoll': 15,
      'leaderType': 'the scholars',
      'type': 'monks',
      'hasClass': false,
      'dndclass': 'scholar',
      'background': 'scholar',
      'title': 'Sir',
      'politicalIdeologyIC': 'pedocratic'
    },
    'theocracy': {
      'economicsRoll': 15,
      'welfareRoll': 30,
      'lawRoll': 15,
      'militaryRoll': -15,
      'arcanaRoll': 35,
      'leaderType': 'the holy',
      'type': 'priests',
      'hasClass': true,
      'dndclass': 'cleric',
      'background': 'acolyte',
      'title': 'High Priest',
      'politicalIdeologyIC': 'theocratic'
    },
    'technocracy': {
      'economicsRoll': 35,
      'welfareRoll': 15,
      'lawRoll': -15,
      'militaryRoll': -5,
      'arcanaRoll': 25,
      'leaderType': 'the engineers',
      'type': 'craftsmen',
      'hasClass': false,
      'dndclass': 'guild artisan',
      'background': 'guild artisan',
      'title': 'Architect',
      'politicalIdeologyIC': 'technocratic'
    }
  },

  'misc': {
    'primaryExport': [
      'barley and oats',
      'beans and corn',
      'nuts and olives',
      'rice',
      'wheat',
      'potatoes and leeks',
      'sugar cane',
      'tobacco',
      'cotton',
      'fruit trees',
      'cabbages and beets',
      'cattle',
      'dairy cows',
      'sheep',
      'carrots and cucumbers',
      'leeks',
      'corn',
      'fish'],
    'primaryCrop': [
      'iron ore',
      'copper ore',
      'cobalt ore',
      'nickel ore',
      'bauxite deposits',
      'gold deposits',
      'silver deposits',
      'clay and granite deposits',
      'salt deposits',
      'quartz deposits',
      'coal deposits',
      'peat deposits',
      'hardwood lumber',
      'softwood lumber',
      'ruby deposits',
      'sapphire deposits',
      'emerald deposits',
      'opal deposits',
      'amethyst deposits',
      'wild game',
      'common fauna used in alchemy',
      'rare fauna used in alchemy'],
    'currentEvent': [
      "an anniversary of a monarch's reign",
      'an anniversary of an important event',
      'an arena event',
      'an arrival of a caravan or ship',
      'an arrival of a circus',
      'an arrival of an important npc',
      'an arrival of marching modrons',
      'an artistic performance',
      'an athletic event',
      'a birth of a child',
      'a birthday of an important npc',
      'a civic festival',
      'a comet appearance',
      'a commemoration of a past tragedy',
      'a consecration of a new temple',
      'a coronation',
      'a council meeting',
      'a equinox or solstice',
      'an execution',
      'a fertility festival',
      'a full moon',
      'a funeral',
      'a graduation of cadets or wizards',
      'a harvest festival',
      'a holy day',
      'an investiture of a knight or other noble',
      'a lunar eclipse',
      'a midsummer festival',
      'a midwinter festival',
      'a migration of monsters',
      "a monarch's ball",
      'a new moon',
      'a new year',
      'a pardoning of a prisoner',
      'a planar conjunction',
      'a planetary alignment',
      'a priestly investiture',
      'a procession of ghosts',
      'a remembrance for soldiers lost in war',
      'a royal address or proclamation',
      'a royal audience day',
      'a signing of a treaty',
      'a solar eclipse',
      'a tournament',
      'a trial',
      'a violent uprising',
      'a wedding or wedding anniversary',
      'a travelling carnival'],
    'microEvent': ["a gnarled old man offers to sell you a 'lucky' trinket for a gold coin",
      'a young boy wants to see a demonstration of your weapon',
      'a little girl is crying because she broke her favorite toy',
      'a little gem falls out of the pocket of the man walking ahead of you',
      'a guard stops you and asks you a few questions because you sort of match the description of a wanted criminal',
      'a simpleton relaxing in the shade challenges you to a milk-drinking contest',
      'a handful of giggling teenagers badger you for some adventuring stories',
      'a middle-aged noble accuses you of cheating with their spouse',
      'a young man bumps into you and falls to the ground.',
      'a man and a woman are having an argument and are blocking your way forward.',
      'a young woman approaches you and offers you a good time. But only to you, not the rest of your party.',
      'a woman empties a chamber pot from a second storey window. Some of it splashes on you.',
      'a group of children suddenly run across the road, chasing each other. Your horse is startled, and rears suddenly. (Maybe ask for a ride check to remain mounted)',
      'a cart blocks the road forward. an elderly man stares at the broken axle and scratches his head.',
      'a cat runs out of nowhere, bats at your foot frantically, then runs back into its hiding place.',
      'a scrawny dog has started following you around. When you stop, it sits next to you and whines gently.',
      'a man lays on the side of the road, unconscious. You can smell alcohol and urine as you pass him.',
      'a man in tattered clothing offers to shine your shoes for a copper piece',
      'a town crier stands on the corner. When you meet his gaze, he offers to recite the news for a coin.',
      "a bard passes you going the other direction atop a horse. as you pass, you can hear him muttering the lyrics to a song you haven't heard.",
      "a person who looks just like someone you know, but shouldn't be here turns the corner onto another street. Do you ignore it? Follow it?",
      "a lost dog starts to follow the group of PC's.",
      'a bauble or trinket found on the ground with the initials P.C.',
      "a man in a dark cloak falls in pace with one of the PC's. Continues walking silently for a block or so.",
      "the PC's are being shadowed. When they turn to look whoever or whatever it is ducks into an alley/behind a barrel/runs away.",
      'street hawkers try to sell the characters nearly everything, or anything. Bonus points if they actually do, and there is a hidden catch.',
      "street clerics spouting off religion. again bonus points if the characters catch a bit that doesn't fit with the way they believe that religion works.",
      'foreigners come to the characters with a book or map and are looking for help in deciphering it. They will not be fluent in the local language.',
      "a 'lady of the evening' approaches the most pious member of the party begging for a religious blessing.",
      'a firebrand preacher is in a town square or on a corner and points out a PC as an example of either piety or paganism.',
      'a young street urchin is being beaten with a riding crop by a wealthier merchant.',
      'a toothless old hag offers to read a PCs fortune in tarot cards.',
      'a schizophrenic beggar begins speaking in tongues or has a conversation with himself.',
      'a random fellow gets thrown out a bar/tavern/inn window with no warning in front of the PCs.',
      "a poor young girl ask you to buy some food for her pet rat (bonus fun if it's actually a tamed dire rat).",
      'a wealthy and overdressed noble is thrown from his horse.',
      'a young prostitute is getting slapped around by her pimp in an alleyway.',
      'a young and very wealthy heir gets drunk and makes a spectacle of himself at a party/ball/dance.',
      'a vengeful wife slaps the shit out of her husband right next to the party.',
      "a young couple is making out in the shadow of a doorway. Was it a priest and a famous noble's daughter, or someone else?!",
      'a runaway horse charges through a marketplace, causing chaos.',
      'a magical device malfunctions blowing the windows out of a shop.',
      'a huge barrel of ale gets loose during a delivery and rolls down the street toward the party.',
      'an older woman lets out a mightily creepy cackle, but it was just over a joke her sister told her.',
      'a young poet asks the party for inspiration.',
      'a down on his luck artist asks if they might commission him for a portrait of one of them.',
      'a cutpurse is tackled and beaten by two city watch officers.',
      "a screaming child throws a tantrum because his/her mother/father won't buy him a trinket.",
      'yYour mama sends you a nice cloth hat with earflaps.',
      'an old man says that his cookoo bird will tell your fortune.',
      'a sleeping dragon (because snorelax is copyrighted) blocks your path',
      'you run into a random acolyte in a temple with a bag on his head handing out grease scrolls',
      "a woman asks you to take this soup to her brother. He works at the store across town. The soup has orange things in it that don't quite look like carrots",
      'a little old man with a heavy foreign accent offers to sell you one of his bizarre monkey-like creatures as a pet.',
      "a middle aged man roughly grabs you by the shoulder, and growls, 'You the fella what knocked up my daughter?!'",
      'two mustachioed gentlemen are in the market square on top of boxes, giving away samples of a new kind of alcoholic beverages. Reactions so far are very mixed.',
      'a bloody knife lays on the ground. Nobody else seems to have noticed it yet.',
      "you witness the guards arresting a man, apparently for deserting his military unit. The young man wails, 'I don't want to fight! I don't want to die! Please! No!'",
      'a young boy excitedly points at you and jumps up and down, soon the party is swarmed by young kids asking for autographs.',
      'two bearded men approach the largest member of your group and offer to sponsor him in a local pit-fighting tournament',
      "as the group is stopped, a particularly gaunt half-elf starts measuring one of the party's arms and legs with a marked string. If permitted, he takes measurements for the entire party. He is an undertaker.",
      'a group of teenage girls are performing a strenuous dance routine on the street corner while a scarred halfling limps around taking donations.',
      'you notice a WaNTED poster with your face on it. The name listed, however, is Vhargle the Black; and the crime is desecration of a holy site.',
      'everyone in this town keeps trying to sell you everything imaginable, but they aLL make a point that they will not, under any circumstances, be selling you their hair. Not that you ever asked.',
      "an old man with piercing blue eyes stops you. He is clearly starving to death. He holds up a purse bulging with coins. 'Does this belong to you?'",
      "a small girl is crying in the road. She looks lost. If asked, her father told her to wait here for him while he went into the pub 'for a minute'. That was six hours ago.",
      'a couple are having sex in a pile of straw near the road. They are loud, and a crowd is starting to gather.',
      'a young urchin is running full speed toward the party carrying a live chicken. Chasing after him is a screaming older man in a fancy cloak, swinging a walking stick.',
      'you find a piece of gold just laying on the ground. No one has noticed it yet.',
      "someone walking by catches your attention. It appears to be a beggar, and he says he'll sketch your caricature in exchange for some soup.",
      "you wake up and head down to the common room of the inn for some breakfast. Your companions aren't awake yet, but you do notice a little commotion outside the window. Looks like some street thugs are accosting a young woman!",
      'you see guards searching the contents of a canvas covered cart that belongs to a woman. She is sitting on the ground crying into her hands.',
      'a store clerk hands you back too much change. If you try to give it back he winks at you and turns to tend to another customer.',
      "as you are entering a store a young man exits forcibly and runs down the street. The clerk appears in front of you right after and asks you 'What way did that thief go!?'",
      'you see a group of young women harassing a young man outside of a bar.',
      'a blind reagent seller shows up at your keep. How do you react?',
      "a street side sailsman hails the players and offers to sell them powerful magic items. He's got loads- 'boots of levitation,' 'rock of undead destruction' 'vampire repellant amulet' and the like. They totally aren't just some boots with five inch heels, or just a rock as big as your head, or a string with garlic on it. No way. Powerful magic in each one.",
      "a couple of town guards approach the party to ask a few questions. They're not intimidating: quite the contrary. The PCs are obviously new arrivals and could bring good tales and rumors. If the meeting goes well the guards might offer them a pint each after their shift.",
      "the party witness a merchant being bullied by two guards and the town's guard captain. after some harsh word exchanges the merchant is forced out of town with threats of jail. This is not a fascist show of force: the merchant refuses to pay the agreed fee to sell on the market and is often accused of selling bad goods, and the guards feel forced to remove him to make place for honest merchants.",
      "as the party enters town they are asked to deposit they're weapons at the town guard armory. If they refuse, there will be questions. at no point is anyone being intolerant and mean, however. The guards just want to make sure the PCs aren't troublemakers, and repeatedly point out that the safety of the populace is what matters.",
      "an old woman approach the party in tears. She proceeds to embrace a random character. 'Oh Garvus, I knew you weren't dead!' She has mistaken the character for her son. The son went missing in action in a war over a decade ago.",
      'a man in rags is standing on a wooden box and proclaiming he had a vision. He proceeds to describe how the god of milk fairies wants the people to stop eating cheese. They should instead burn all the cheese ceremonially at midnight to receive magic powers. Locals ignore him.',
      "a parchment flies through the street and the wind flaps it on your face. It is a saucy love letter to 'My burly bear' from 'Your naughty little minx'.",
      "a demented (and obviously harmless) old man causes a scene by blaming a random female character for being his adulterous wife. He then tries to pick a fight with the burliest male character, blaming he has seduced the old man's wife.",
      'there is a maimed beggar on the street, asking for alms. Someone recognizes him as the famous adventurer / war hero, who was his/her idol when s/he was a child.',
      'a fake mystic offers to read their fortune. It is all cold reading and fake, but it is a good act, just without an ounce of magic in it.',
      'despite it being winter, there are butterflies following a small girl walking past the characters.',
      'the characters see an innkeeper refuse to serve a person of different ethnicity/species/something followed by obviously racist slurs.',
      "an annoying youngster starts pestering a magician (or someone looking like one!) to teach him magic, because he wants to 'kill monsters, loot dungeons and get all the girls!'.",
      'the character witness a public execution for a relatively minor crime. The crowd cheers on as the executioners struts his stuff like a rock star on the stage before getting on with the business.',
      'a cart transporting beer/bread/fresh fruit has fallen over. a mob of poor people are now grabbing free goodies, while the teamster tries to shout them off.',
      "two middle aged bards have a high brow version of a rap battle in the street. They're competing against one another to entice customers into their respective establishments.",
      "a group of junior mages are using a cantrip leveled version of 'gust of wind' to blow up womens' skirts.",
      'a traveling troupe of monks showcase their skills for food and minor coin.',
      "an aquatic elf offers underwater tours at a coastal city's port.",
      "a carnival is in town, showing off their newest ride: a vertical iron wheel with seats meant to let people see the whole town at once. They nicknamed it the 'ferric wheel' due to it being made mostly of iron.",
      'a merchant in a heavily corroded outfit tries to sell his dishwashing invention. (contains a black pudding)',
      'you notice two thugs following a young woman from a distance, trying to look inconspicuous.',
      'a gnome accosts you, insisting you help him find his runaway pet cat, a tabby named Blingtangle. He offers no reward.']
  },
  'terrain': {
    'temperate': {
      'start': ['seacoast', 'forest', 'hills', 'plains', 'mountains', 'river coast'],
      'seacoast': {
        'origin': [
          'a coastal harbor',
          'a calm, coastal bay',
          'a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'the mouth of a river',
          'the confluence of two rivers',
          'a series of natural springs',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'
        ],
        'vegetation': ['sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': ['shrubs', 'bush', 'windswept trees', 'windswept trees', 'windswept trees']
      },
      'forest': {
        'origin': [
          'a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'the mouth of a river',
          'a deep freshwater river',
          'a river that runs through the forest',
          'a series of natural springs',
          'a well-traveled crossroads',
          'a road that passes through the forests',
          'a water source and a well-traveled road leading through the forest'
        ],
        'vegetation': ['sparse', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick', 'thick', 'thick', 'thick'],
        'plants': ['oak trees', 'oak trees', 'oak trees', 'pine trees', 'maple trees', 'birch trees', 'ash trees', 'elm trees', 'fir trees', 'spruce trees', 'sycamore trees', 'alder trees', 'cypress trees', 'yew trees']
      },
      'hills': {
        'origin': ['a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['sparse', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'plains': {
        'origin': ['a wide, navigable river',
          'a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'lush', 'thick'],
        'plants': []
      },
      'mountains': {
        'origin': ['a large freshwater lake',
          'a river navigable by small craft',
          'a series of natural springs',
          'a road that connects two other cities',
          'a road that leads through the mountains',
          'a trade route through the mountains',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'lush', 'thick'],
        'plants': []
      },
      'river coast': {
        'origin': ['a coastal harbor',
          'a calm, coastal bay',
          'a wide, navigable river',
          'a river navigable by small craft'],
        'vegetation': ['sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': []
      }
    },
    'tropical': {
      'start': ['seacoast', 'forest', 'hills', 'plains', 'mountains', 'river coast', 'jungle', 'volcanic field'],
      'seacoast': {
        'origin': ['a coastal harbor',
          'a calm, coastal bay',
          'a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'the mouth of a river',
          'the confluence of two rivers',
          'a series of natural springs',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'forest': {
        'origin': ['a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'the mouth of a river',
          'a deep freshwater river',
          'a river that runs through the forest',
          'a series of natural springs',
          'a well-traveled crossroads',
          'a road that passes through the forests',
          'a water source and a well-traveled road leading through the forest'],
        'vegetation': ['sparse', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'hills': {
        'origin': ['a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads'],
        'vegetation': ['sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'plains': {
        'origin': ['a wide, navigable river',
          'a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'lush', 'thick'],
        'plants': []
      },
      'mountains': {
        'origin': ['a large freshwater lake',
          'a river navigable by small craft',
          'a series of natural springs',
          'a road that connects two other cities',
          'a road that leads through the mountains',
          'a trade route through the mountains',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'lush', 'thick'],
        'plants': []
      },
      'river coast': {
        'origin': ['a coastal harbor',
          'a calm, coastal bay',
          'a wide, navigable river',
          'a river navigable by small craft'],
        'vegetation': ['sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'jungle': {
        'origin': ['a river navigable by small craft',
          'a series of natural springs',
          'a road that connects two other cities',
          'a road that leads through the jungle',
          'a trade route through the jungle',
          'a water source and a well-traveled road that leads through the jungle'],
        'vegetation': ['sparse', 'lush', 'thick', 'thick', 'thick', 'thick', 'thick', 'thick', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'volcanic field': {
        'origin': ['a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'the mouth of a river',
          'a series of natural springs',
          'a series of natural springs',
          'a series of natural springs',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'sparse', 'sparse', 'sparse', 'lush'],
        'plants': []
      }
    },
    'arid': {
      'start': ['desert', 'hills', 'plains', 'mountains', 'river coast', 'wasteland', 'oasis'],
      'desert': {
        'origin': ['a coastal harbor',
          'a calm, coastal bay',
          'a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'the mouth of a river',
          'the confluence of two rivers',
          'a series of natural springs',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'forest': {
        'origin': ['a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'the mouth of a river',
          'a deep freshwater river',
          'a river that runs through the forest',
          'a series of natural springs',
          'a well-traveled crossroads',
          'a road that passes through the forests',
          'a water source and a well-traveled road leading through the forest'],
        'vegetation': ['desolate', 'desolate', 'sparse', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'hills': {
        'origin': ['a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'lush', 'thick'],
        'plants': []
      },
      'plains': {
        'origin': ['a wide, navigable river',
          'a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'lush', 'thick'],
        'plants': []
      },
      'mountains': {
        'origin': ['a large freshwater lake',
          'a river navigable by small craft',
          'a series of natural springs',
          'a road that connects two other cities',
          'a road that leads through the mountains',
          'a trade route through the mountains',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'lush', 'thick'],
        'plants': []
      },
      'river coast': {
        'origin': ['a coastal harbor',
          'a calm, coastal bay',
          'a wide, navigable river',
          'a river navigable by small craft'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'wasteland': {
        'origin': ['a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'sparse', 'sparse', 'sparse', 'lush'],
        'plants': []
      },
      'oasis': {
        'origin': ['a series of natural springs',
          'a series of natural springs',
          'a large oasis of water',
          'a large oasis of water',
          'a large oasis of water',
          'a large oasis of water',
          'a water source and a well-traveled road'],
        'vegetation': ['sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': []
      }
    },
    'polar': {
      'start': ['seacoast', 'forest', 'hills', 'plains', 'mountains', 'river coast', 'tundra', 'ice sheet', 'seacoast'],
      'seacoast': {
        'origin': ['a coastal harbor',
          'a calm, coastal bay',
          'a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'the mouth of a river',
          'the confluence of two rivers',
          'a series of natural springs',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'forest': {
        'origin': ['a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'the mouth of a river',
          'a deep freshwater river',
          'a river that runs through the forest',
          'a series of natural springs',
          'a well-traveled crossroads',
          'a road that passes through the forests',
          'a water source and a well-traveled road leading through the forest'],
        'vegetation': ['desolate', 'desolate', 'sparse', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'hills': {
        'origin': ['a large freshwater lake',
          'a wide, navigable river',
          'a river navigable by small craft',
          'a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'desolate', 'sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'plains': {
        'origin': ['a wide, navigable river',
          'a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'lush', 'thick'],
        'plants': []
      },
      'mountains': {
        'origin': ['a large freshwater lake',
          'a river navigable by small craft',
          'a series of natural springs',
          'a road that connects two other cities',
          'a road that leads through the mountains',
          'a trade route through the mountains',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'sparse', 'sparse', 'sparse', 'sparse', 'sparse', 'lush', 'thick'],
        'plants': []
      },
      'river coast': {
        'origin': ['a coastal harbor',
          'a calm, coastal bay',
          'a wide, navigable river',
          'a river navigable by small craft'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'sparse', 'lush', 'lush', 'lush', 'lush', 'thick', 'thick', 'thick'],
        'plants': []
      },
      'tundra': {
        'origin': ['a wide, navigable river',
          'a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'sparse', 'sparse', 'sparse', 'lush'],
        'plants': []
      },
      'ice sheet': {
        'origin': ['a wide, navigable river',
          'a road traveled by merchants on the way to another, larger city',
          'a well maintained road',
          'a road that connects two other cities',
          'a well-traveled crossroads',
          'a water source and a well-traveled road'],
        'vegetation': ['desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'desolate', 'sparse', 'sparse', 'sparse', 'lush'],
        'plants': []
      }
    }
  }

}
